"""Constants mirrored from the Nest API.

Source of truth: apps/api/src/timetables/timetables.constants.ts
Keep the two files in sync; bump SOLVER_CONTRACT_SCHEMA_VERSION there first.
"""

TIMETABLE_SOLVER_QUEUE = "timetable-solver"
TIMETABLE_SOLVER_JOB = "solve-timetable"

SOLVER_CONTRACT_SCHEMA_VERSION = 1

TIMETABLE_STATUS = {
    "GENERATING": "GENERATING",
    "DRAFT": "DRAFT",
    "PUBLISHED": "PUBLISHED",
    "ARCHIVED": "ARCHIVED",
    "FAILED": "FAILED",
}

PERIOD_SLOT_KIND = {
    "PERIOD": "PERIOD",
    "BREAK": "BREAK",
    "ASSEMBLY": "ASSEMBLY",
    "LUNCH": "LUNCH",
}

ROOM_TYPE = {
    "CLASSROOM": "CLASSROOM",
    "SCIENCE_LAB": "SCIENCE_LAB",
    "COMPUTER_LAB": "COMPUTER_LAB",
    "SPORTS": "SPORTS",
    "AUDITORIUM": "AUDITORIUM",
    "OTHER": "OTHER",
}

# Editor collision codes returned in 409 bodies by slot move/swap (unused by
# the worker; mirrored for parity with timetables.constants.ts).
SLOT_CONFLICT_CODE = {
    "CLASS_BUSY": "CLASS_BUSY",
    "TEACHER_BUSY": "TEACHER_BUSY",
    "ROOM_BUSY": "ROOM_BUSY",
    "TEACHER_UNAVAILABLE": "TEACHER_UNAVAILABLE",
    "INVALID_PERIOD": "INVALID_PERIOD",
}

# Soft-constraint violation codes reported by the solver on DRAFT results.
VIOLATION_SUBJECT_NOT_SPREAD = "SUBJECT_NOT_SPREAD"
VIOLATION_TEACHER_LOAD_IMBALANCE = "TEACHER_LOAD_IMBALANCE"

VIOLATION_CODE = {
    "SUBJECT_NOT_SPREAD": VIOLATION_SUBJECT_NOT_SPREAD,
    "TEACHER_LOAD_IMBALANCE": VIOLATION_TEACHER_LOAD_IMBALANCE,
}

# Actionable infeasibility hint codes reported when generation FAILED.
HINT_TEACHER_OVERLOADED = "TEACHER_OVERLOADED"
HINT_CLASS_OVERALLOCATED = "CLASS_OVERALLOCATED"
HINT_ROOM_TYPE_SCARCE = "ROOM_TYPE_SCARCE"
HINT_AVAILABILITY_CONFLICT = "AVAILABILITY_CONFLICT"
HINT_BLOCK_SIZE_IMPOSSIBLE = "BLOCK_SIZE_IMPOSSIBLE"
HINT_GENERATION_INTERRUPTED = "GENERATION_INTERRUPTED"
HINT_UNKNOWN = "UNKNOWN"

INFEASIBLE_HINT_CODE = {
    "TEACHER_OVERLOADED": HINT_TEACHER_OVERLOADED,
    "CLASS_OVERALLOCATED": HINT_CLASS_OVERALLOCATED,
    "ROOM_TYPE_SCARCE": HINT_ROOM_TYPE_SCARCE,
    "AVAILABILITY_CONFLICT": HINT_AVAILABILITY_CONFLICT,
    "BLOCK_SIZE_IMPOSSIBLE": HINT_BLOCK_SIZE_IMPOSSIBLE,
    "GENERATION_INTERRUPTED": HINT_GENERATION_INTERRUPTED,
    "UNKNOWN": HINT_UNKNOWN,
}

# Preflight issue codes (mirrored for parity; the worker reuses the
# CLASS_OVERALLOCATED / TEACHER_OVERLOADED spellings as hint codes above).
PREFLIGHT_CODE = {
    "NO_ALLOCATIONS": "NO_ALLOCATIONS",
    "MISSING_INSTRUCTOR": "MISSING_INSTRUCTOR",
    "AMBIGUOUS_INSTRUCTOR": "AMBIGUOUS_INSTRUCTOR",
    "CLASS_OVERALLOCATED": "CLASS_OVERALLOCATED",
    "TEACHER_OVERLOADED": "TEACHER_OVERLOADED",
    "ROOM_TYPE_MISSING": "ROOM_TYPE_MISSING",
    "BLOCK_SIZE_INVALID": "BLOCK_SIZE_INVALID",
}

# Solver result statuses.
STATUS_OPTIMAL = "OPTIMAL"
STATUS_FEASIBLE = "FEASIBLE"
STATUS_INFEASIBLE = "INFEASIBLE"
STATUS_ERROR = "ERROR"

# Server-side cap on solver wall time; requests above this are clamped.
SOLVER_MAX_TIME_LIMIT_SECONDS = 300
SOLVER_DEFAULT_TIME_LIMIT_SECONDS = 120

ISO_DAY_NAMES = {
    1: "Monday",
    2: "Tuesday",
    3: "Wednesday",
    4: "Thursday",
    5: "Friday",
    6: "Saturday",
    7: "Sunday",
}
